# -*- coding: utf-8 -*-
"""SQL_TASK3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5voKETrMGqoy0r845t5kLF4snmrWVTO
"""

import sqlite3
import pandas as pd

# 1. Connect to database and build your schema
conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

cursor.executescript("""
CREATE TABLE customers (
    customer_id INTEGER PRIMARY KEY AUTOINCREMENT,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
    category_id INTEGER PRIMARY KEY AUTOINCREMENT,
    category_name TEXT NOT NULL,
    description TEXT
);

CREATE TABLE vendors (
    vendor_id INTEGER PRIMARY KEY AUTOINCREMENT,
    vendor_name TEXT NOT NULL,
    contact_email TEXT
);

CREATE TABLE products (
    product_id INTEGER PRIMARY KEY AUTOINCREMENT,
    product_name TEXT NOT NULL,
    category_id INTEGER,
    vendor_id INTEGER,
    unit_price REAL NOT NULL CHECK (unit_price >= 0),
    stock_qty INTEGER DEFAULT 0,
    FOREIGN KEY (category_id) REFERENCES categories(category_id),
    FOREIGN KEY (vendor_id) REFERENCES vendors(vendor_id)
);

CREATE TABLE orders (
    order_id INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_id INTEGER NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending','Confirmed','Shipped','Delivered','Cancelled')),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE order_lines (
    line_id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price REAL NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders(order_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE payments (
    payment_id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER UNIQUE NOT NULL,
    payment_date TIMESTAMP,
    method TEXT CHECK (method IN ('Card','PayPal','Bank Transfer','Wallet')),
    amount REAL NOT NULL,
    status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending','Paid','Failed','Refunded')),
    FOREIGN KEY (order_id) REFERENCES orders(order_id)
);
""")

#Requirements
# • customer_name: concatenated first_name + ' ' + last_name
# • total_orders: count of distinct orders placed by each customer
# • total_spent: sum of (quantity × unit_price) across all order lines for each customer
# • customer_rank: rank by total_spent descending — use RANK() window function
# • Include ONLY customers who have placed at least 1 order
# • Order the result by customer_rank ascending

# 2. Add sample data so the query returns a result
cursor.executescript("""
INSERT INTO customers (first_name, last_name, email) VALUES
('Alice', 'Smith', 'alice@email.com'),
('Bob', 'Jones', 'bob@email.com'),
('Charlie', 'Brown', 'charlie@email.com');

INSERT INTO orders (customer_id, status) VALUES (1, 'Delivered'), (1, 'Delivered'), (2, 'Delivered'), (3, 'Delivered');

INSERT INTO order_lines (order_id, product_id, quantity, unit_price) VALUES
(1, 101, 2, 10.0),
(2, 102, 1, 15.0),
(3, 103, 1, 50.0),
(4, 104, 5, 20.0);
""")
conn.commit()


query = """
SELECT
    c.first_name || ' ' || c.last_name AS customer_name,
    COUNT(DISTINCT o.order_id) AS total_orders,
    SUM(ol.quantity * ol.unit_price) AS total_spent,
    RANK() OVER (ORDER BY SUM(ol.quantity * ol.unit_price) DESC) AS customer_rank
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN order_lines ol ON o.order_id = ol.order_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_spent DESC;
"""

# 4. Fetch and display the  table output
df_result = pd.read_sql_query(query, conn)
display(df_result)