# -*- coding: utf-8 -*-
"""SQL-TASK2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gA8CEJVMDiLVdYW2_bUOueY0HCPOQJHq
"""

import pandas as pd
import sqlite3

# Create an in-memory SQLite database connection
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

print("Setup complete. Environment ready.")

# Define a messy, unnormalized dataset (0NF)
# Issues: Non-atomic values (multiple text books), redundant data, mixed concerns.
data_0nf = {
    "Student_ID": [101, 101, 102, 103, 104],
    "Student_Name": ["Alice", "Alice", "Bob", "Charlie", "David"],
    "Course_Code": ["CS101", "MATH201", "CS101", "CS102", "MATH201"],
    "Course_Name": ["Intro to CS", "Calculus I", "Intro to CS", "Data Structures", "Calculus I"],
    "Instructor_ID": ["INS_01", "INS_02", "INS_01", "INS_03", "INS_05"],
    "Instructor_Name": ["Dr. Smith", "Dr. Jones", "Dr. Smith", "Dr. Alan", "Dr. Jones"],
    "Instructor_Office": ["Room 401", "Room 502", "Room 401", "Room 401", "Room 502"],
    "Textbooks_Required": ["Python Basics, Intro to CLI", "Calculus Vol 1", "Python Basics, Intro to CLI", "Algorithms Vol 1", "Calculus Vol 1"],
    "Grade": ["A", "B", "A", "B+", "A-"]
}

df_0nf = pd.DataFrame(data_0nf)
df_0nf.to_sql('Unnormalized_Leasing', conn, index=False, if_exists='replace')

print("\n--- Unnormalized Data (0NF) ---")
df_0nf

# Flattening the Textbooks_Required column to ensure atomicity
df_1nf = df_0nf.assign(Textbooks_Required=df_0nf['Textbooks_Required'].str.split(', ')).explode('Textbooks_Required')

# Save to SQL
df_1nf.to_sql('Table_1NF', conn, index=False, if_exists='replace')

print("--- 1NF Data (Atomic values enforced) ---")
print(f"Row count increased from {len(df_0nf)} to {len(df_1nf)} due to flattening.")
df_1nf

# 1. Students Table
df_students_2nf = df_1nf[['Student_ID', 'Student_Name']].drop_duplicates().reset_index(drop=True)

# 2. Courses & Instructors Table (We will fix instructor redundancies in 3NF)
df_courses_2nf = df_1nf[['Course_Code', 'Course_Name', 'Instructor_ID', 'Instructor_Name', 'Instructor_Office']].drop_duplicates().reset_index(drop=True)

# 3. Course Textbooks Table
df_textbooks_2nf = df_1nf[['Course_Code', 'Textbooks_Required']].drop_duplicates().reset_index(drop=True)

# 4. Student Grades Table (Fully dependent on both Student and Course)
df_grades_2nf = df_1nf[['Student_ID', 'Course_Code', 'Grade']].drop_duplicates().reset_index(drop=True)

# Save to SQL
df_students_2nf.to_sql('Students_2NF', conn, index=False, if_exists='replace')
df_courses_2nf.to_sql('Courses_2NF', conn, index=False, if_exists='replace')
df_textbooks_2nf.to_sql('Textbooks_2NF', conn, index=False, if_exists='replace')
df_grades_2nf.to_sql('Grades_2NF', conn, index=False, if_exists='replace')

print("--- 2NF Schema Created ---")
print("\n[Students_2NF]: PK = Student_ID")
display(df_students_2nf)
print("\n[Courses_2NF]: PK = Course_Code")
display(df_courses_2nf)
print("\n[Grades_2NF]: PK = (Student_ID, Course_Code)")
display(df_grades_2nf)

# Extract Instructors into a separate table to eliminate transitive dependency
df_instructors_3nf = df_courses_2nf[['Instructor_ID', 'Instructor_Name', 'Instructor_Office']].drop_duplicates().reset_index(drop=True)

# Clean up Courses table to only keep the Instructor_ID as a Foreign Key
df_courses_3nf = df_courses_2nf[['Course_Code', 'Course_Name', 'Instructor_ID']].drop_duplicates().reset_index(drop=True)

# Save to SQL
df_instructors_3nf.to_sql('Instructors_3NF', conn, index=False, if_exists='replace')
df_courses_3nf.to_sql('Courses_3NF', conn, index=False, if_exists='replace')

print("--- 3NF Schema Refinement ---")
print("\n[Courses_3NF] (No transitive dependency):")
display(df_courses_3nf)
print("\n[Instructors_3NF] (New isolated table):")
display(df_instructors_3nf)

# Creating a scenario that is in 3NF but VIOLATES BCNF
# Composite Primary Key for this registration table: (Student_ID, Course_Code)
bcnf_scen_data = {
    "Student_ID": [101, 102, 101, 103],
    "Course_Code": ["CS101", "CS101", "MATH201", "CS101"],
    "Instructor_ID": ["INS_A", "INS_B", "INS_C", "INS_A"]
    # Notice: INS_A only teaches CS101. Knowing Instructor_ID tells you the Course_Code.
}

df_3nf_violating_bcnf = pd.DataFrame(bcnf_scen_data)
df_3nf_violating_bcnf.to_sql('Registration_3NF_Violating_BCNF', conn, index=False, if_exists='replace')

print("--- Table in 3NF but NOT in BCNF ---")
display(df_3nf_violating_bcnf)

print("\nFunctional Dependencies present:")
print("1. (Student_ID, Course_Code) -> Instructor_ID  (Primary Key dependency)")
print("2. Instructor_ID -> Course_Code               (Instructor only teaches one specific course)")
print("\nWhy it violates BCNF: Instructor_ID determines Course_Code, but Instructor_ID is NOT a superkey!")

import pandas as pd
import sqlite3
conn_challenge = sqlite3.connect(':memory:')
challenge_data ={
    "Visit_ID": [5001,5001,5002,5003],
    "Student_ID":[101,101,102,104],
    "Student_Name":["Alice","Alice","Bob","David"],
    "Doctor_ID":["DOC_XYZ", "DOC_XYZ", "DOC_ABC", "DOC_XYZ"],
    "Doctor_Name":["Dr.Evans","Dr.Evans", "Dr. Green", "Dr.Evans"],
    "Doctorr_Clinic":["General Medicine","General Medicine","Sports Med", "General Medicine"],
    "Prescriptions":["Amoxicillin,Ibuprofen","Amoxcillin,Ibuprofen", "Bandages", "Vitamin D"],

}
df_challenge =pd.DataFrame(challenge_data)
df_challenge.to_sql('Patient_Visits_0NF',conn_challenge,index=False, if_exists='replace')
print("---Challenge Dataset(0NF)---")
df_challenge

import sqlite3
import pandas as pd

#  in-memory SQLite connection
conn_challenge = sqlite3.connect(':memory:')

#  raw data
challenge_data = {
    "Visit_ID": [5001, 5001, 5002, 5003],
    "Student_ID": [101, 101, 102, 104],
    "Student_Name": ["Alice", "Alice", "Bob", "David"],
    "Doctor_ID": ["DOC_XYZ", "DOC_XYZ", "DOC_ABC", "DOC_XYZ"],
    "Doctor_Name": ["Dr.Evans", "Dr.Evans", "Dr. Green", "Dr.Evans"],
    "Doctor_Clinic": ["General Medicine", "General Medicine", "Sports Med", "General Medicine"],
    "Prescriptions": ["Paracetamol,Ibuprofen", "Paracetamol,Ibuprofen", "Vitamin D", "Antibiotic"]
}

#  DataFrame
df_challenge = pd.DataFrame(challenge_data)

# Normalize Prescriptions into 1NF
df_1nf = df_challenge.assign(
    Prescriptions=df_challenge['Prescriptions'].str.split(',')
).explode('Prescriptions')

df_1nf = df_1nf.reset_index(drop=True)

df_1nf.to_sql('Patients_Visits_1NF', conn_challenge, index=False, if_exists='replace')

print("---1NF Data---")
print(df_1nf)
