# -*- coding: utf-8 -*-
"""Autogen_groq.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NPhWNm8O6tJ3PkW6V6L6NNGYhvjEe6ee
"""

#!pip install -q autogenstudio pyngrok

#!autogenstudio version

import os
import getpass

if "GROQ_API_KEY" not in os.environ:
  os.environ["GROQ_API_KEY"] =getpass.getpass("GROQ_API_KEY")


"NGROK_AUTH_TOKEN" ==getpass.getpass("GROQ_API_KEY")

#!ngrok config add-authtoken "ngrok key"

#For running Autogen Studio in google colab

import multiprocessing

import time

from pyngrok import ngrok

def run_autogen_studio():

# Launch AutoGen Studio on port 8081

  !autogenstudio ui --port 8081 --host 0.0.0.0

# Start AutoGen Studio in a background process

process = multiprocessing.Process(target=run_autogen_studio)

process.start()

# Wait a moment for the server to spin up

time.sleep(5)

# Open the ngrok tunnel to port 8081

public_url = ngrok.connect(8081)

print("\n" + "="*60)

print(f"[SUCCESS] AutoGen Studio is running!")

print(f"Click the link below to open the UI:")

print(f"{public_url}")

print("="*60 + "\n")

import os
import asyncio
from autogen_agentchat.agents import AssistantAgent
from autogen_agentchat.teams import RoundRobinGroupChat
from autogen_agentchat.conditions import MaxMessageTermination
from autogen_ext.models.openai import OpenAIChatCompletionClient

async def run_team():
 # Fetch the Groq API key you securely entered in Cell 2
 groq_key = os.environ["GROQ_API_KEY"]

 # Define Groq model clients with the correct model_info settings
 researcher_model = OpenAIChatCompletionClient(
 model="llama-3.1-8b-instant",
 base_url="https://api.groq.com/openai/v1",
 api_key=groq_key,
 model_info={
 "vision": False,
 "function_calling": True,
 "json_output": True,
 "structured_output": True,
 "family": "unknown"
 }
 )

 editor_model = OpenAIChatCompletionClient(
 model="llama-3.3-70b-versatile",
 base_url="https://api.groq.com/openai/v1",
 api_key=groq_key,
 model_info={
 "vision": False,
 "function_calling": True,
 "json_output": True,
 "structured_output": True,
 "family": "unknown"
 }
 )

 # Define the individual Agents
 researcher = AssistantAgent(
 name="Researcher",
 model_client=researcher_model,
 system_message="You are an expert researcher. Provide a highly detailed summary using clear Markdown formatting."
 )

 editor = AssistantAgent(
 name="Editor",
 model_client=editor_model,
 system_message="You are a strict editor. Critique the researcher's work and optimize it for professional delivery."
 )

 # Orchestrate the workflow team
 team = RoundRobinGroupChat(
 participants=[researcher, editor],
 termination_condition=MaxMessageTermination(max_messages=4)
 )

 # Run the prompt
 print("--- Starting Multi-Agent Session ---")
 async for message in team.run_stream(task="Explain why Groq LPUs provide higher throughput for LLMs than standard GPUs."):
   if hasattr(message, "source") and hasattr(message, "content"):
        print(f"\n\033[1m[{message.source}]\033[0m: {message.content}")
        print("-" * 40)
   else:
        print("\n--- Final Result ---")
        print(message)
        print("-" * 40)

# Execute the async loop inside Google Colab
await run_team()

# Install packages
!pip install -q autogen-agentchat autogen-ext openai requests nest_asyncio

import os
import asyncio
import nest_asyncio

from autogen_agentchat.agents import AssistantAgent
from autogen_agentchat.teams import RoundRobinGroupChat
from autogen_agentchat.conditions import MaxMessageTermination
from autogen_ext.models.openai import OpenAIChatCompletionClient

nest_asyncio.apply()

# =====================================
# GROQ CONFIGURATION
# =====================================

groq_key = os.environ["GROQ_API_KEY"]  # or paste your key directly

model_client = OpenAIChatCompletionClient(
    model="llama-3.3-70b-versatile",
    api_key=groq_key,
    base_url="https://api.groq.com/openai/v1",
    model_info={
        "vision": False,
        "function_calling": True,
        "json_output": True,
        "structured_output": True,
        "family": "unknown"
    }
)

# =====================================
# RESEARCH AGENT
# =====================================

researcher = AssistantAgent(
    name="Researcher",
    model_client=model_client,
    system_message="""
You are an expert researcher.

Research the topic thoroughly.
Provide facts, analysis and findings.
"""
)

# =====================================
# TOOL AGENT
# =====================================

tool_agent = AssistantAgent(
    name="ToolAgent",
    model_client=model_client,
    system_message="""
You are a tool specialist.

Perform calculations, provide structured data,
and assist the researcher with technical tasks.
"""
)

# =====================================
# EDITOR AGENT
# =====================================

editor = AssistantAgent(
    name="Editor",
    model_client=model_client,
    system_message="""
You are a professional editor.

Improve grammar, structure,
formatting and readability.

Convert output into a professional report.
"""
)

# =====================================
# USER PROXY AGENT
# =====================================

user_proxy = AssistantAgent(
    name="UserProxy",
    model_client=model_client,
    system_message="""
You are the human approval checkpoint.

Review the final report.

Ask:
'Do you approve this report?'

Provide final approval comments.
"""
)

# =====================================
# TEAM WORKFLOW
# =====================================

team = RoundRobinGroupChat(
    participants=[
        researcher,
        tool_agent,
        editor,
        user_proxy
    ],
    termination_condition=MaxMessageTermination(max_messages=8)
)

# =====================================
# RUN WORKFLOW
# =====================================

async def main():

    task = """
    Research how AI agents are transforming
    supply chain management.

    Create a professional report with:
    1. Introduction
    2. Benefits
    3. Challenges
    4. Real-world Applications
    5. Conclusion
    """

    print("\nSTARTING MULTI-AGENT WORKFLOW\n")

    async for message in team.run_stream(task=task):

        if hasattr(message, "source") and hasattr(message, "content"):

            print("\n" + "="*70)
            print(f"AGENT: {message.source}")
            print("="*70)
            print(message.content)

asyncio.get_event_loop().run_until_complete(main())

