# -*- coding: utf-8 -*-
"""ML_Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n0fhxFIz6GDhxep9FPQ3_E33PJqyvNcZ
"""

#pip install mlflow

import mlflow

import mlflow.sklearn

import pandas as pd

import matplotlib.pyplot as plt

from sklearn.datasets import load_breast_cancer

from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import (

accuracy_score,

precision_score,

recall_score,

f1_score,

ConfusionMatrixDisplay

)
mlflow.end_run()

#CELL 3-Load & split data

data= load_breast_cancer()

X,y =data.data, data.target

#stratify-y ensures the same malignant/benign ratio in train & test

X_train, X_test, y_train, y_test =train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)


print(f"Train:{X_train.shape} Test:{X_test.shape}")

#Output: Train: (455, 30) Test: (114,30)


#CELL 4-Configure MLFlow tracking URI and experiment

#SQLite keeps everything in a local file - great for elab demos.

# In Azure ML, replace this with your workspace tracking URI.

mlflow.set_tracking_uri("sqlite:///mlflow.db")

#All runs logged below will appear under this experiment tab in the Ul

mlflow.set_experiment("breast-cancer-classifier")

#CELL 5-RUN A: Manual logging

# We log everything explicitly so we understand

# exactly what autolog() does later.

MAX_DEPTH=4

MIN_SAMPLES = 5

CRITERION ="gini"

with mlflow.start_run(run_name="manual-logging") as run:

#Step 1: Log every hyperparameter we pass to the model-

    mlflow.log_param("max_depth", MAX_DEPTH)

    mlflow.log_param("min_samples_Split", MIN_SAMPLES)

    mlflow.log_param("criterion", CRITERION)

    mlflow.log_param(" rendem state", 42)



#Step 2: Train

clf = DecisionTreeClassifier(
    max_depth=MAX_DEPTH,
    min_samples_split=MIN_SAMPLES,
    criterion=CRITERION,
    random_state=42,
)

clf.fit(X_train, y_train)

y_pred=clf.predict(X_test)

#Step 3: Log evaluation metrics

mlflow.log_metric("accuracy", accuracy_score(y_test, y_pred))

mlflow.log_metric("precision", precision_score(y_test, y_pred))

mlflow.log_metric("recall", recall_score(y_test, y_pred))

mlflow.log_metric("f1", f1_score(y_test, y_pred))

#Step 4: Save confusion matrix as a PNG artefact

#Artefacts are files (images, CSVs, plots) attached to a run

fig, ax= plt.subplots(figsize=(5,4))

ConfusionMatrixDisplay.from_predictions(y_test, y_pred, ax=ax)

plt.tight_layout()

plt.savefig("confusion_matrix.png")

mlflow.log_artifact("confusion_matrix.png") # uploads file to run

plt.close()

#Step 5: Log the serialised model object itself

mlflow.sklearn.log_model(clf, "decision-tree-model")

print(f"Run ID: {run.info.run_id}")

print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")

#CELL 6-RUN B: Autolog (same result, zero manual code)


#miflow.sklearn.autolog() monkey-patches fit() so that the

# moment you call glf.fit() it automatically captures:

#all constructor parameters

#training metrics

#the fitted model

# an input example (sample of Xtrain)

# a model signature (inferred input/output schema)

mlflow.sklearn.autolog(

log_input_examples = True, #attaches a sample of Xtrain

log_model_signatures = True,#infers & stores input/output schema

log_models= True     #saves the fitted model object

)
mlflow.end_run()

with mlflow.start_run(run_name="autolog-run"):

    clf2 = DecisionTreeClassifier(max_depth=6, random_state=42)

    clf2.fit(X_train, y_train)

#autolog fires at fit() -nothing else needed!

    print("autolog run complete check the Ul for logged params & metrics")

#CELL 7-Launch the MLFlow Tracking Ul in Golab

#This starts the server in the background on port 5000.

#In Colab, use the port-forwarding panel (or install pyngrek).c

#!miflow ui--backend-store-url sqlite:///mlflow.db --port 5000 &

print("Ul running at: http://localhost:5000")

#Navigate to the experiment, select both runs, click Compare

# Task:

# Complete the MLFlow tracking snippet below so that it correctly:

# (a) Logs max depth and n estimators as parameters

# (b) Logs accuracy and 11 as metrics

# (c) Logs and registers the model under the name "iris-rf-classifier"

# (d) Sets a tag "team" with value "data-science

#coding_task.py-fill in all blanks

#Python

import mlflow
import mlflow.sklearn
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score
from sklearn.model_selection import train_test_split


mlflow.set_tracking_uri("sqlite:///quiz.db")
mlflow.set_experiment("quiz-experiment")

# Load and split dataset
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0
)

MAX_DEPTH = 5
N_ESTIMATORS = 100

with mlflow.start_run(run_name="quiz-run"):

# (a) Log parameters
    mlflow.log_param("max_depth", MAX_DEPTH)
    mlflow.log_param("n_estimators", N_ESTIMATORS)

    # Train the model
    model = RandomForestClassifier(
        max_depth=MAX_DEPTH, n_estimators=N_ESTIMATORS, random_state=42
    )

    model.fit(X_train, y_train)
    preds = model.predict(X_test)

    # (b) Log metrics
    mlflow.log_metric("accuracy", accuracy_score(y_test, preds))
    mlflow.log_metric("f1", f1_score(y_test, preds, average="macro"))

    # (c) Log and register the model
    mlflow.sklearn.log_model(
        sk_model=model,  # the fitted model object
        artifact_path="random-forest-model",
        registered_model_name="iris-rf-classifier",  # registry name
    )

    # (d) Set a tag
    mlflow.set_tag("team", "data-science")


