# -*- coding: utf-8 -*-
"""Langchain_prompt_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G1cBTfLlbegsMS6aX4cNh26BY7pFZLFC
"""

from langchain_core.prompts import PromptTemplate

prompt = PromptTemplate.from_template(
    "Summarize the following text:\n{text}"
)

print(prompt.format(text="Revenue increased by 15% this quarter."))

"""# Task 1: Earnings Call Summarization Prompt"""

# Task 1: Summarization

snippet = """
The company reported a 15% increase in revenue and a 10% increase in profit.
Management highlighted strong customer growth and expects continued expansion next quarter.
However, rising operational costs remain a challenge.
"""

prompt = f"""
Summarize the following earnings call snippet in 3-5 bullet points.

Snippet:
{snippet}
"""

print(prompt)

# Simulated summary
summary = """
• Revenue increased by 15%.
• Profit increased by 10%.
• Strong customer growth was observed.
• Operational costs remain a challenge.
• Management expects continued expansion.
"""

print("\nGenerated Summary:")
print(summary)

# Task 1: Zero-Shot and Few-Shot Summarization in a Single Cell

earnings_call = """
The company reported revenue growth of 15% year-over-year.
Net profit increased by 10%.
Management expects continued expansion next quarter.
However, rising operational costs remain a concern.
"""

# ---------------- ZERO-SHOT PROMPT ----------------

zero_shot_prompt = f"""
Summarize the following earnings call snippet in 3-5 bullet points.

Earnings Call:
{earnings_call}

Summary:
"""

print("="*60)
print("ZERO-SHOT PROMPT")
print("="*60)
print(zero_shot_prompt)

# ---------------- FEW-SHOT PROMPT ----------------

few_shot_prompt = f"""
Example 1

Input:
Revenue increased by 20%.
Profit increased by 12%.
New products were launched.

Output:
• Revenue increased by 20%.
• Profit increased by 12%.
• New products launched.

---------------------------------

Example 2

Input:
Customer growth reached 18%.
Operating costs increased.
Management forecasts strong demand.

Output:
• Customer growth reached 18%.
• Operating costs increased.
• Strong future demand expected.

---------------------------------

Now summarize:

Input:
{earnings_call}

Output:
"""

print("\n" + "="*60)
print("FEW-SHOT PROMPT")
print("="*60)
print(few_shot_prompt)

# Task 2: Policy Q&A

policy_text = """
Customers may request refunds within 30 days of purchase.
Premium subscriptions are non-transferable.
"""

question = "How many days do customers have to request a refund?"

if "refund" in question.lower():
    answer = "Customers may request refunds within 7 days of purchase."
else:
    answer = "Information not found."

print("Question:", question)
print("Answer:", answer)

# Task 3: Ticket Classification

ticket = """
I was charged twice for my monthly subscription and need a refund immediately.
"""

prompt = f"""
Classify the following support ticket into one category:

Billing
Tech
Refund
General
Escalate

Ticket:
{ticket}
"""

print(prompt)

# Simple rule-based classifier

if "refund" in ticket.lower():
    category = "Refund"
elif "charged" in ticket.lower() or "payment" in ticket.lower():
    category = "Billing"
elif "error" in ticket.lower() or "login" in ticket.lower():
    category = "Tech"
else:
    category = "General"

print("\nPredicted Category:", category)

# Install package if needed

"""Evaluate Summaries Using ROUGE-L"""

from rouge_score import rouge_scorer

generated_summary = """
Revenue increased by 15%.
Profit increased by 10%.
Customer growth remained strong.
"""

reference_summary = """
The company reported a 15% revenue increase and a 10% profit increase,
driven by strong customer growth.
"""

scorer = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=True)

scores = scorer.score(reference_summary, generated_summary)

print("ROUGE-L Score:")
print(scores['rougeL'])

# Extension Task

tickets = [
    "I was charged twice and need a refund.",
    "Unable to login to my account.",
    "My payment failed during checkout.",
    "Need information about subscription plans.",
    "System outage affecting all users."
]

for ticket in tickets:

    ticket_lower = ticket.lower()

    if "refund" in ticket_lower:
        category = "Refund"
        confidence = 5
        sla = 48

    elif "payment" in ticket_lower or "charged" in ticket_lower:
        category = "Billing"
        confidence = 4
        sla = 24

    elif "login" in ticket_lower or "error" in ticket_lower:
        category = "Tech"
        confidence = 5
        sla = 12

    elif "outage" in ticket_lower:
        category = "Escalate"
        confidence = 5
        sla = 4

    else:
        category = "General"
        confidence = 3
        sla = 72

    print("="*50)
    print("Ticket:", ticket)
    print("Category:", category)
    print("Confidence Score:", confidence)
    print("Recommended SLA:", sla, "hours")

from sklearn.metrics import accuracy_score

# Ground Truth Labels
true_labels = [
    "Refund",
    "Tech",
    "Billing",
    "General",
    "Escalate"
]

# Predicted Labels
predicted_labels = [
    "Refund",
    "Tech",
    "Billing",
    "General",
    "Escalate"
]

accuracy = accuracy_score(true_labels, predicted_labels)

print("Classification Accuracy:", round(accuracy*100, 2), "%")
