# -*- coding: utf-8 -*-
"""audio_text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15yFETKy0b7KlqHcWk5Q1zwDh4BDnirg2
"""

#!pip install -q yt-dlp openai-whisper ffmpeg-python
#!apt-get install -y ffmpeg

from yt_dlp import YoutubeDL
import ffmpeg

# Step 1: download video
def download_video(url):
    ydl_opts = {
        "format": "mp4/best",
        "outtmpl": "video.mp4",
        "quiet": True
    }

    with YoutubeDL(ydl_opts) as ydl:
        ydl.download([url])

    return "video.mp4"


# Step 2: extract audio
def extract_audio(video_path):
    audio_path = "audio.mp3"

    (
        ffmpeg
        .input(video_path)
        .output(audio_path)
        .run(overwrite_output=True, quiet=True)
    )

    return audio_path

import whisper

def transcribe_audio(audio_path):
    model = whisper.load_model("base")

    result = model.transcribe(audio_path)

    return result["text"]

url = "https://youtube.com/shorts/A2NIWDI_41g?si=355_Q6VwDODmeQIc"

print("Downloading video...")
video = download_video(url)

print("Extracting audio...")
audio = extract_audio(video)

print("Transcribing...")
text = transcribe_audio(audio)

print("\n===== TRANSCRIPTION OUTPUT =====\n")
print(text)
