# -*- coding: utf-8 -*-
"""Youtube_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15pipreFYCW2P5GDG3sP8JbstO8RMUivW
"""

#!pip install -U hume yt-dlp

from hume import HumeClient
import os
import json
import time
from yt_dlp import YoutubeDL

import hume

print("Hume version:", getattr(hume, "__version__", "unknown"))

from hume import HumeClient

client = HumeClient(api_key="dummy")

print("\nAvailable attributes:")
print(dir(client))

from yt_dlp import YoutubeDL

YOUTUBE_URL = "https://youtu.be/rMLwiVrK3Fw?si=di4Cu0w8op0kCALq"

def download_video(url):
    ydl_opts = {
        "format": "mp4/best",
        "outtmpl": "video.%(ext)s",
        "quiet": False
    }

    with YoutubeDL(ydl_opts) as ydl:
        ydl.download([url])

download_video(YOUTUBE_URL)

print("Download complete")

import os
import asyncio
import json
from yt_dlp import YoutubeDL
from hume import AsyncHumeClient

# SET YOUR API KEY
os.environ["HUME_API_KEY"] = ""


# FIXED YOUTUBE DOWNLOADER (NO JS ERROR)
def download_video(url):
    ydl_opts = {
        "format": "best[ext=mp4]/best",
        "outtmpl": "video.mp4",
        "quiet": True,

        #  FIX YT-DLP YOUTUBE ISSUE
        "extractor_args": {
            "youtube": {
                "player_client": ["android", "web"]
            }
        }
    }

    with YoutubeDL(ydl_opts) as ydl:
        ydl.download([url])

    return "video.mp4"

#!pip install -q deepface yt-dlp opencv-python-headless

import cv2
from deepface import DeepFace
from collections import Counter

video_path = "video.mp4"

cap = cv2.VideoCapture(video_path)

emotions = []

frame_count = 0

while True:
    success, frame = cap.read()

    if not success:
        break

    frame_count += 1

    # Analyze every 30th frame
    if frame_count % 30 != 0:
        continue

    try:
        result = DeepFace.analyze(
            frame,
            actions=["emotion"],
            enforce_detection=False,
            silent=True
        )

        if isinstance(result, list):
            emotion = result[0]["dominant_emotion"]
        else:
            emotion = result["dominant_emotion"]

        emotions.append(emotion)

    except Exception:
        pass

cap.release()

counts = Counter(emotions)

print("\nEmotion Summary")
print("=" * 40)

total = sum(counts.values())

for emotion, count in counts.most_common():
    pct = round((count / total) * 100, 2)
    print(f"{emotion}: {pct}%")

import matplotlib.pyplot as plt

plt.figure(figsize=(7,7))
plt.pie(
    counts.values(),
    labels=counts.keys(),
    autopct='%1.1f%%'
)

plt.title("Emotion Distribution")
plt.show()
